cmake_minimum_required(VERSION 4.0)
project(POO_2024_1_Herencia)

set(CMAKE_CXX_STANDARD 20)

add_executable(POO_2024_1_Herencia main.cpp
        Libro.cpp
        Libro.h
        Comunes.h
        Comunes.cpp
        Novelas.cpp
        Novelas.h
        Enciclopedia.cpp
        Enciclopedia.h
        Espacio.cpp
        Espacio.h
        Estante.cpp
        Estante.h
        EstanteVertical.cpp
        EstanteVertical.h
        EstanteHorizontal.cpp
        EstanteHorizontal.h
        Biblioteca.cpp
        Biblioteca.h
)
