cmake_minimum_required(VERSION 4.0)
project(2024_2_POO_Lab6)

set(CMAKE_CXX_STANDARD 20)

add_executable(2024_2_POO_Lab6 main.cpp
        Cliente.cpp
        Cliente.h
        Comunes.cpp
        Comunes.h
        Restaurante.cpp
        Restaurante.h
        Plato.cpp
        Plato.h
        Plato.h)
