cmake_minimum_required(VERSION 4.0)
project(2024_1_Polimorfismo_autoReferencia)

set(CMAKE_CXX_STANDARD 20)

add_executable(2024_1_Polimorfismo_autoReferencia main.cpp
        Libro.cpp
        Libro.h
        Comunes.h
        Comunes.cpp
        Enciclopedia.cpp
        Enciclopedia.h
        Novela.cpp
        Novela.h
        Revista.cpp
        Revista.h
        Nodo.cpp
        Nodo.h
        Lista.cpp
        Lista.h
        Estante.cpp
        Estante.h
        Biblioteca.cpp
        Biblioteca.h
)
