cmake_minimum_required(VERSION 4.0)
project(2025__1_LAB6_POO)

set(CMAKE_CXX_STANDARD 20)

add_executable(2025__1_LAB6_POO main.cpp
        Infraccion.cpp
        Infraccion.h
        Comunes.h
        Comunes.cpp
        Empresa.cpp
        Empresa.h
        Multa.cpp
        Multa.h
        MinisterioDeTransporte.cpp
        MinisterioDeTransporte.h)
